name: Test
on:
  push:
    branch: [ main ]
  pull_request:
    branch: [ main ]
  release:
    types: [ published ]
jobs:
  atilo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with: 
          python-version: 3.11.2

      - name: Install Modules
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Test
        id: test
        run: |
          ./atilo help
          ./atilo images
